# Generated by Django 3.2 on 2022-10-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_collections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collections',
            new_name='Collection',
        ),
    ]
