# Generated by Django 3.2 on 2022-10-04 16:50

from django.db import migrations, models
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_collections_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='collection', variations={'thumb': {'crop': True, 'height': 215, 'width': 351}}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
