# Generated by Django 3.2 on 2022-10-05 19:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20221004_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Coleção', 'verbose_name_plural': 'Coleções'},
        ),
        migrations.AddField(
            model_name='blog',
            name='front_cover',
            field=stdimage.models.StdImageField(default=django.utils.timezone.now, force_min_size=False, upload_to='Blog', variations={'thumb': {'crop': True, 'height': 215, 'width': 351}}, verbose_name='Imagem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='Blog', variations={'thumb': {'crop': True, 'height': 215, 'width': 351}}, verbose_name='Imagem'),
        ),
    ]
