# Generated by Django 3.2 on 2022-10-05 19:44

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20221005_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='front_cover',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='Blog', variations={'thumb': {'crop': True, 'height': 824, 'width': 1595}}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='collection', variations={'thumb': {'crop': True, 'height': 1350, 'width': 1080}}, verbose_name='Imagem'),
        ),
    ]
